baseURL = "https://LeonwxZ.github.io/"
locale = "en-US"
title = "Wenxu Zheng"
theme = "PaperMod"

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]


[params]
defaultTheme = "auto"
ShowReadingTime = true
ShowCodeCopyButtons = true
ShowPostNavLinks = true

math = true


[params.homeInfoParams]

Title = "Hi, I'm Wenxu Zheng 👋"

Content = """
Robotics | Embodied AI | Embedded Systems
"""


[[menu.main]]

identifier = "publications"
name = "Publications"
url = "/papers/"
weight = 10


[[menu.main]]

identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 20


[[menu.main]]

identifier = "blog"
name = "Blog"
url = "/Blogs/"
weight = 30


[[menu.main]]

identifier = "about"
name = "About"
url = "/about/"
weight = 40